version: '3'

services:
  spring-mysql:
    image: mysql:5.7       
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=test
    - MYSQL_USER=spring
    - MYSQL_PASSWORD=spring    
    springboot-app:
      image: chetanchilhate/web-dev:v1
      ports: 
      - 8088:8088
      depends_on:
        - spring-mysql        