# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      mysql: 
        image: mysql:5.7
        env:
          MYSQL_USER: spring
          MYSQL_PASSWORD: spring 
          MYSQL_DATABASE: test     
          MYSQL_ROOT_PASSWORD: root   
        ports:  
        - 3306:3306 
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:   
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build & Push Docker image 
      uses: mr-smithers-excellent/docker-build-push@v5    
      with:
        image: chetanchilhate/web-dev
        tags: v1, latest
        registry: docker.io    
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
